# Generated by Django 2.2.6 on 2020-05-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='picture',
            new_name='picture_url',
        ),
    ]
